from chempy import Substance

H = Substance.from_formula("H")
He = Substance.from_formula("He")
Li = Substance.from_formula("Li")
Be = Substance.from_formula("Be")
B = Substance.from_formula("B")
C = Substance.from_formula("C")
N = Substance.from_formula("N")
O = Substance.from_formula("O")
F = Substance.from_formula("F")
Ne= Substance.from_formula("Ne")
Na = Substance.from_formula("Na")
Mg = Substance.from_formula("Mg")
Al = Substance.from_formula("Al")
Si = Substance.from_formula("Si")
P = Substance.from_formula("P")
S = Substance.from_formula("S")
Cl = Substance.from_formula("Cl")
Ar = Substance.from_formula("Ar")
K = Substance.from_formula("K")
Ca = Substance.from_formula("Ca")
Sc = Substance.from_formula("Sc")
Ti = Substance.from_formula("Ti")
V = Substance.from_formula("V")
Cr = Substance.from_formula("Cr")
Mn = Substance.from_formula("Mn")
Fe = Substance.from_formula("Fe")
Co = Substance.from_formula("Co")
Ni = Substance.from_formula("Ni")
Cu = Substance.from_formula("Cu")
Zn = Substance.from_formula("Zn")
Ga = Substance.from_formula("Ga")
Ge = Substance.from_formula("Ge")
As = Substance.from_formula("As")
Se = Substance.from_formula("Se")
Br = Substance.from_formula("Br")
Kr = Substance.from_formula("Kr")
Rb = Substance.from_formula("Rb")
Sr = Substance.from_formula("Sr")
Y = Substance.from_formula("Y")
Zr = Substance.from_formula("Zr")
Nb = Substance.from_formula("Nb")
Mol = Substance.from_formula("Mo")
Tc = Substance.from_formula("Tc")
Ru = Substance.from_formula("Ru")
Rh = Substance.from_formula("Rh")
Pd = Substance.from_formula("Pd")
Ag = Substance.from_formula("Ag")
Cd = Substance.from_formula("Cd")
In = Substance.from_formula("In")
Sn = Substance.from_formula("Sn")
Sb = Substance.from_formula("Sb")
Te = Substance.from_formula("Te")
I = Substance.from_formula("I")
Xe = Substance.from_formula("Xe")
Cs = Substance.from_formula("Cs")
Ba = Substance.from_formula("Ba")
La = Substance.from_formula("La")
Ce = Substance.from_formula("Ce")
Pr = Substance.from_formula("Pr")
Ndy = Substance.from_formula("Nd")
Pm = Substance.from_formula("Pm")
Sm = Substance.from_formula("Sm")
Eu = Substance.from_formula("Eu")
Gd = Substance.from_formula("Gd")
Tb = Substance.from_formula("Tb")
Dy = Substance.from_formula("Dy")
Ho = Substance.from_formula("Ho")
Er = Substance.from_formula("Er")
Tm = Substance.from_formula("Tm")
Yb = Substance.from_formula("Yb")
Lu = Substance.from_formula("Lu")
Hf = Substance.from_formula("Hf")
Ta = Substance.from_formula("Ta")
W = Substance.from_formula("W")
Re = Substance.from_formula("Re")
Os = Substance.from_formula("Os")
Ir = Substance.from_formula("Ir")
Pt = Substance.from_formula("Pt")
Au = Substance.from_formula("Au")
Hg = Substance.from_formula("Hg")
Tl = Substance.from_formula("Tl")
Pb = Substance.from_formula("Pb")
Bi = Substance.from_formula("Bi")
Po = Substance.from_formula("Po")
At = Substance.from_formula("At")
Rn = Substance.from_formula("Rn")
Fr = Substance.from_formula("Fr")
Ra = Substance.from_formula("Ra")
Ac = Substance.from_formula("Ac")
Th = Substance.from_formula("Th")
Pa = Substance.from_formula("Pa")
U = Substance.from_formula("U")
Np = Substance.from_formula("Np")
Pu = Substance.from_formula("Pu")
Am = Substance.from_formula("Am")
Cm = Substance.from_formula("Cm")
Bk = Substance.from_formula("Bk")
Cf = Substance.from_formula("Cf")
Es = Substance.from_formula("Es")
Fm = Substance.from_formula("Fm")
Md = Substance.from_formula("Md")
No = Substance.from_formula("No")
Lr = Substance.from_formula("Lr")
Rf = Substance.from_formula("Rf")
Db = Substance.from_formula("Db")
Sg = Substance.from_formula("Sg")
Bh = Substance.from_formula("Bh")
Hs = Substance.from_formula("Hs")
Mt = Substance.from_formula("Mt")
Ds = Substance.from_formula("Ds")
Rg = Substance.from_formula("Rg")
Cn = Substance.from_formula("Cn")
Nh = Substance.from_formula("Nh")
Fl = Substance.from_formula("Fl")
Mc = Substance.from_formula("Mc")
Lv = Substance.from_formula("Lv")
Ts = Substance.from_formula("Ts")
Og = Substance.from_formula("Og")








# transfer = True
#
# while transfer:
#     with open('elementlist.csv', newline='') as el:
#         reader = csv.reader(el)
#         data = list(reader)
#     with open('elements.py', mode='w') as f_obj:
#         element_writer = data.



